<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CreateMatchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('matches')->insert([
            [
                'team_id1'           => 52,
                'team_color1'        => 5,
                'team_id2'           => 53,
                'team_color2'        => 8,
                'conference_name'    => 'howard_test_stt0',
                'type'               => 1,
                'team_owner'         => 1,
                'start_date'         => '2022-01-01',
                'start_time'         => '10:01:00',
                'place'              => NULL,
                'referee'            => NULL,
                'linesman'           => NULL,
                'fourth_referee'     => NULL,
                'add_referee'        => NULL,
                'substitute_referee' => NULL,
                'var_referee'        => NULL,
                'weather'            => NULL,
                'pitch_type'         => NULL,
                'situation'          => 1,
                'number_people'      => 10,
                'round1_time'        => 1,
                'round2_time'        => 1,
                'round3_time'        => NULL,
                'round4_time'        => NULL,
                'additional_time1'   => NULL,
                'additional_time2'   => NULL,
                'additional_time3'   => NULL,
                'additional_time4'   => NULL,
                'rest_time'          => NULL,
                'extra_time'         => NULL,
                'penalty'            => 1,
                'comment'            => NULL,
                'status'             => 0,
                'created_at'         => '2022-06-15 13:47:45',
                'updated_at'         => '2022-07-13 18:32:18',
                'deleted_at'         => NULL,
                'created_by'         => 9
            ],
            [
                'team_id1'           => 52,
                'team_color1'        => 5,
                'team_id2'           => 53,
                'team_color2'        => 8,
                'conference_name'    => 'howard_test_stt1',
                'type'               => 1,
                'team_owner'         => 1,
                'start_date'         => '2022-01-01',
                'start_time'         => '10:01:00',
                'place'              => NULL,
                'referee'            => NULL,
                'linesman'           => NULL,
                'fourth_referee'     => NULL,
                'add_referee'        => NULL,
                'substitute_referee' => NULL,
                'var_referee'        => NULL,
                'weather'            => NULL,
                'pitch_type'         => NULL,
                'situation'          => 1,
                'number_people'      => 10,
                'round1_time'        => 1,
                'round2_time'        => 1,
                'round3_time'        => NULL,
                'round4_time'        => NULL,
                'additional_time1'   => NULL,
                'additional_time2'   => NULL,
                'additional_time3'   => NULL,
                'additional_time4'   => NULL,
                'rest_time'          => NULL,
                'extra_time'         => NULL,
                'penalty'            => 1,
                'comment'            => NULL,
                'created_at'         => '2022-06-15 13:47:45',
                'updated_at'         => '2022-07-13 18:32:18',
                'deleted_at'         => NULL,
                'created_by'         => 9
            ],
            [
                'team_id1'           => 52,
                'team_color1'        => 5,
                'team_id2'           => 53,
                'team_color2'        => 8,
                'conference_name'    => 'howard_test_stt2',
                'type'               => 1,
                'team_owner'         => 1,
                'start_date'         => '2022-01-01',
                'start_time'         => '10:01:00',
                'place'              => NULL,
                'referee'            => NULL,
                'linesman'           => NULL,
                'fourth_referee'     => NULL,
                'add_referee'        => NULL,
                'substitute_referee' => NULL,
                'var_referee'        => NULL,
                'weather'            => NULL,
                'pitch_type'         => NULL,
                'situation'          => 1,
                'number_people'      => 10,
                'round1_time'        => 1,
                'round2_time'        => 1,
                'round3_time'        => NULL,
                'round4_time'        => NULL,
                'additional_time1'   => NULL,
                'additional_time2'   => NULL,
                'additional_time3'   => NULL,
                'additional_time4'   => NULL,
                'rest_time'          => NULL,
                'extra_time'         => NULL,
                'penalty'            => 1,
                'comment'            => NULL,
                'status'             => 2,
                'created_at'         => '2022-06-15 13:47:45',
                'updated_at'         => '2022-07-13 18:32:18',
                'deleted_at'         => NULL,
                'created_by'         => 9
            ],
        ]);
    }
}
